apiVersion: v1
data:
  ## Tenant credentials, base64 encoded (cat config.env | base64)
  ##  export MINIO_ROOT_USER="minio"
  ##  export MINIO_ROOT_PASSWORD="minio123"
  ##  export MINIO_STORAGE_CLASS_STANDARD="EC:2"
  ##  export MINIO_BROWSER="on"
  config.env: {{your.config.JTW}}
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
type: Opaque