apiVersion: v2
appVersion: 2.2.1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.5.3
description: The official Helm chart to deploy Apache Airflow, a platform to programmatically author, schedule, and monitor workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/docs/apache-airflow/stable/_images/pin_large.png
keywords:
- apache
- airflow
- workflow
- scheduler
maintainers:
- email: dev@airflow.apache.org
  name: Apache Airflow PMC
name: airflow
sources:
- https://github.com/apache/airflow
type: application
version: 1.3.0
